export const MENUS = [{
    "order_code": "AA01",
    "name_en": "GrilledSpicyChicken",
    "name": "辛味チキン",
    "price": 300,
    "calorie": 374,
    "salt": 2.2
}, {
    "order_code": "AA02",
    "name_en": "GrilledSkeweredLamb",
    "name": "アロスティチーニ",
    "price": 400,
    "calorie": 224,
    "salt": 0.6
}, {
    "order_code": "AA03",
    "name_en": "SautedSpinachwithBacon",
    "name": "ほうれん草のソテー",
    "price": 200,
    "calorie": 123,
    "salt": 1.3
}, {
    "order_code": "AA04",
    "name_en": "FriedShrimp",
    "name": "ポップコーンシュリンプ",
    "price": 300,
    "calorie": 215,
    "salt": 1.4
}, {
    "order_code": "AA05",
    "name_en": "GrilledEscargots",
    "name": "エスカルゴのオーブン焼き",
    "price": 400,
    "calorie": 256,
    "salt": 1.6
}, {
    "order_code": "AA06",
    "name_en": "GreenPeaswithBacon",
    "name": "柔らか青豆の温サラダ",
    "price": 200,
    "calorie": 214,
    "salt": 0.9
}, {
    "order_code": "AA07",
    "name_en": "GrilledSpicySausage",
    "name": "チョリソー",
    "price": 400,
    "calorie": 393,
    "salt": 2.0
}, {
    "order_code": "AA08",
    "name_en": "GrilledPotatowithCheese",
    "name": "フリウリ風フリコ",
    "price": 300,
    "calorie": 419,
    "salt": 1.9
}, {
    "order_code": "AA10",
    "name_en": "GrilledGreenMusselswithVegetableSalsa",
    "name": "ムール貝のガーリック焼き",
    "price": 400,
    "calorie": 164,
    "salt": 1.3
}, {
    "order_code": "AA11",
    "name_en": "SautedCabbagewithAnchovy",
    "name": "キャベツとアンチョビのソテー",
    "price": 200,
    "calorie": 85,
    "salt": 1.7
}, {
    "order_code": "AA12",
    "name_en": "BuffaloMozzarellaCheesewithTomato",
    "name": "フレッシュチーズとトマトのサラダ",
    "price": 300,
    "calorie": 195,
    "salt": 0.4
}, {
    "order_code": "AA13",
    "name_en": "PickledMixVegetables",
    "name": "白菜のミックスピクルス",
    "price": 200,
    "calorie": 66,
    "salt": 1.5
}, {
    "order_code": "AA14",
    "name_en": "SalamifromMilano",
    "name": "熟成ミラノサラミ",
    "price": 300,
    "calorie": 95,
    "salt": 1.1
}, {
    "order_code": "AA16",
    "name_en": "ProsciuttofromParma",
    "name": "プロシュート",
    "price": 400,
    "calorie": 162,
    "salt": 1.8
}, {
    "order_code": "AA17",
    "name_en": "GrilledPotatowithCheese&Anchovy",
    "name": "アンチョビのフリコ",
    "price": 400,
    "calorie": 551,
    "salt": 4.1
}, {
    "order_code": "AA21",
    "name_en": "GrilledSkeweredLamb",
    "name": "アロスティチーニ Wサイズ",
    "price": 800,
    "calorie": 448,
    "salt": 1.2
}, {
    "order_code": "AA22",
    "name_en": "BuffaloMozzarellaCheesewithTomato",
    "name": "フレッシュチーズとトマトのサラダ Wサイズ",
    "price": 600,
    "calorie": 390,
    "salt": 0.8
}, {
    "order_code": "AA23",
    "name_en": "ProsciuttofromParma",
    "name": "プロシュート Wサイズ",
    "price": 800,
    "calorie": 284,
    "salt": 3.6
}, {
    "order_code": "AA24",
    "name_en": "SalamifromMilano",
    "name": "熟成ミラノサラミ Wサイズ",
    "price": 600,
    "calorie": 190,
    "salt": 2.2
}, {
    "order_code": "AA25",
    "name_en": "GrilledPotatowithCheese",
    "name": "スパイシーフリコ",
    "price": 350,
    "calorie": 425,
    "salt": 3.3
}, {
    "order_code": "AA26",
    "name_en": "ItalianInnardsStew",
    "name": "イタリア風もつ煮込み",
    "price": 350,
    "calorie": 188,
    "salt": 0.7
}, {
    "order_code": "BR01",
    "name_en": "Beer",
    "name": "キリン一番搾り ジョッキ",
    "price": 400,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "BR02",
    "name_en": "Beer",
    "name": "キリン一番搾り グラスビール",
    "price": 300,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "BR03",
    "name_en": "Beer",
    "name": "サントリーオールフリー",
    "price": 250,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "BR04",
    "name_en": "Beer",
    "name": "ストロングゼロ ダブルレモン",
    "price": 350,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "BR05",
    "name_en": "Beer",
    "name": "ラコンブリッコラ",
    "price": 300,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "DB01",
    "name_en": "DrinkBar",
    "name": "セットドリンクバー",
    "price": 200,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "DE01",
    "name_en": "Tiramisu",
    "name": "ティラミス クラシコ",
    "price": 300,
    "calorie": 229,
    "salt": 0.1
}, {
    "order_code": "DE02",
    "name_en": "Meringata",
    "name": "メリンガータ",
    "price": 200,
    "calorie": 139,
    "salt": 0.0
}, {
    "order_code": "DE03",
    "name_en": "CoffeeJellywithMilkGelato",
    "name": "コーヒーゼリー(ミルクアイスのせ)",
    "price": 300,
    "calorie": 162,
    "salt": 0.1
}, {
    "order_code": "DE05",
    "name_en": "ItalianGelato",
    "name": "イタリアンジェラート",
    "price": 250,
    "calorie": 100,
    "salt": 0.1
}, {
    "order_code": "DE06",
    "name_en": "ItalianCustardPudding",
    "name": "イタリアンプリン",
    "price": 250,
    "calorie": 216,
    "salt": 0.1
}, {
    "order_code": "DE07",
    "name_en": "ChocolateCake",
    "name": "チョコレートケーキ",
    "price": 300,
    "calorie": 166,
    "salt": 0.1
}, {
    "order_code": "DE08",
    "name_en": "Meringata&ItalianCustardPudding",
    "name": "プリンとメリンガータの盛合せ",
    "price": 400,
    "calorie": 355,
    "salt": 0.1
}, {
    "order_code": "DE10",
    "name_en": "PannacottawithCaramelSauce&Apple",
    "name": "キャラメルりんごのパンナコッタ",
    "price": 400,
    "calorie": 210,
    "salt": 0.2
}, {
    "order_code": "DE11",
    "name_en": "LemonSorbet",
    "name": "すっきりレモンのシャーベット",
    "price": 200,
    "calorie": 127,
    "salt": 0.0
}, {
    "order_code": "DE12",
    "name_en": "Tiramisu&ItalianCustardPudding",
    "name": "プリンとティラミス クラシコの盛合せ",
    "price": 500,
    "calorie": 445,
    "salt": 0.2
}, {
    "order_code": "DE13",
    "name_en": "TruffleIceCream",
    "name": "トリフアイスクリーム",
    "price": 350,
    "calorie": 164,
    "salt": 0.1
}, {
    "order_code": "DE14",
    "name_en": "CoffeeJellywithTiramisu",
    "name": "とろけるティラミス&コーヒーゼリー",
    "price": 400,
    "calorie": 284,
    "salt": 0.1
}, {
    "order_code": "DE15",
    "name_en": "CoffeeJellywithItalianGelato",
    "name": "イタリアンジェラートのせコーヒーゼリー",
    "price": 350,
    "calorie": 182,
    "salt": 0.1
}, {
    "order_code": "DE16",
    "name_en": "Tiramisu",
    "name": "ティラミスクラシコ ファミリーサイズ",
    "price": 1800,
    "calorie": 1374,
    "salt": 0.6
}, {
    "order_code": "DG01",
    "name_en": "DoriawithMeatSauce",
    "name": "ミラノ風ドリア",
    "price": 300,
    "calorie": 521,
    "salt": 2.5
}, {
    "order_code": "DG02",
    "name_en": "DoriawithMeatSauce&Cheese",
    "name": "チーズたっぷりミラノ風ドリア",
    "price": 400,
    "calorie": 722,
    "salt": 3.4
}, {
    "order_code": "DG03",
    "name_en": "DoriawithMeatSauce&Egg",
    "name": "半熟卵のミラノ風ドリア",
    "price": 350,
    "calorie": 611,
    "salt": 2.7
}, {
    "order_code": "DG04",
    "name_en": "DoriawithMeatSauce&Caponata",
    "name": "いろどり野菜のミラノ風ドリア",
    "price": 400,
    "calorie": 570,
    "salt": 3.0
}, {
    "order_code": "DG05",
    "name_en": "DoriawithMeatSauce&SetPetitFocaccia",
    "name": "セットプチフォッカ付きミラノ風ドリア",
    "price": 400,
    "calorie": 626,
    "salt": 2.9
}, {
    "order_code": "DG06",
    "name_en": "SpinachGratinwithBacon&Salami",
    "name": "ほうれん草のグラタン",
    "price": 400,
    "calorie": 521,
    "salt": 1.9
}, {
    "order_code": "DG07",
    "name_en": "Tomato&CreamGratinwithShrimp",
    "name": "エビクリームグラタンペンネ",
    "price": 400,
    "calorie": 517,
    "salt": 2.1
}, {
    "order_code": "DG08",
    "name_en": "Paella",
    "name": "シーフードパエリア",
    "price": 600,
    "calorie": 595,
    "salt": 3.6
}, {
    "order_code": "DG09",
    "name_en": "ShrimpRisottowithTomato&Cream",
    "name": "エビと野菜のトマトクリームリゾット",
    "price": 400,
    "calorie": 320,
    "salt": 2.4
}, {
    "order_code": "DG10",
    "name_en": "HAYASHI StewwithTurmericRice",
    "name": "ハヤシ&ターメリックライス",
    "price": 500,
    "calorie": 676,
    "salt": 3.9
}, {
    "order_code": "DG11",
    "name_en": "HAYASHI StewwithTurmericRice",
    "name": "半熟卵のハヤシ&ターメリックライス",
    "price": 550,
    "calorie": 766,
    "salt": 4.1
}, {
    "order_code": "MT01",
    "name_en": "HamburgSteak",
    "name": "ハンバーグステーキ",
    "price": 400,
    "calorie": 560,
    "salt": 2.8
}, {
    "order_code": "MT02",
    "name_en": "GrilledChickenwithVegetableSalsa",
    "name": "若鶏のディアボラ風",
    "price": 500,
    "calorie": 672,
    "salt": 2.7
}, {
    "order_code": "MT03",
    "name_en": "HamburgSteakwithCheese&TomatoSauce",
    "name": "イタリアンハンバーグ",
    "price": 500,
    "calorie": 670,
    "salt": 2.9
}, {
    "order_code": "MT04",
    "name_en": "GrilledChickenwithCheese&TomatoSauce",
    "name": "柔らかチキンのチーズ焼き",
    "price": 500,
    "calorie": 716,
    "salt": 2.7
}, {
    "order_code": "MT07",
    "name_en": "HamburgSteakwithVegetableSalsa",
    "name": "ディアボラ風ハンバーグ",
    "price": 500,
    "calorie": 632,
    "salt": 3.1
}, {
    "order_code": "MT08",
    "name_en": "HamburgSteakwithMushroomDemi-GlaceSauce",
    "name": "デミグラスソースのハンバーグ",
    "price": 500,
    "calorie": 606,
    "salt": 3.1
}, {
    "order_code": "MT09",
    "name_en": "RibSteak",
    "name": "リブステーキ",
    "price": 1000,
    "calorie": 606,
    "salt": 2.0
}, {
    "order_code": "MT13",
    "name_en": "GrilledLambwithVegetableSalsa&Mushroom Tomato",
    "name": "ラムときのこのきこり風",
    "price": 700,
    "calorie": 560,
    "salt": 3.4
}, {
    "order_code": "MT14",
    "name_en": "BIGGrilledSpicyChicken",
    "name": "骨付きももの辛味チキン",
    "price": 600,
    "calorie": 397,
    "salt": 2.3
}, {
    "order_code": "MT15",
    "name_en": "HamburgSteakwithGrilledSpicySausage",
    "name": "チョリソーとハンバーグの盛合せ",
    "price": 550,
    "calorie": 675,
    "salt": 3.7
}, {
    "order_code": "PA01",
    "name_en": "SpaghettiTARAKOSauce",
    "name": "タラコソースシシリー風",
    "price": 400,
    "calorie": 550,
    "salt": 2.0
}, {
    "order_code": "PA02",
    "name_en": "SpaghettiwithMeatSauce",
    "name": "ミートソースボロニア風",
    "price": 400,
    "calorie": 571,
    "salt": 2.8
}, {
    "order_code": "PA03",
    "name_en": "SpaghettiPEPERONCINO",
    "name": "ペペロンチーノ",
    "price": 300,
    "calorie": 497,
    "salt": 1.6
}, {
    "order_code": "PA04",
    "name_en": "SpaghettiwithTomato&Bacon",
    "name": "パルマ風スパゲッティ",
    "price": 400,
    "calorie": 716,
    "salt": 2.7
}, {
    "order_code": "PA05",
    "name_en": "SpaghettiCARBONARA",
    "name": "カルボナーラ",
    "price": 500,
    "calorie": 738,
    "salt": 2.1
}, {
    "order_code": "PA06",
    "name_en": "SpaghettiwithShrimp&Broccoli,Tomato&Cream",
    "name": "エビとブロッコリーのオーロラソース",
    "price": 500,
    "calorie": 668,
    "salt": 2.9
}, {
    "order_code": "PA08",
    "name_en": "SpaghettiAGLIOOLIO",
    "name": "アーリオ・オーリオ",
    "price": 300,
    "calorie": 497,
    "salt": 1.5
}, {
    "order_code": "PA09",
    "name_en": "ShortPastawithTomatoBacon&Chilli",
    "name": "アラビアータ",
    "price": 400,
    "calorie": 601,
    "salt": 2.5
}, {
    "order_code": "PA10",
    "name_en": "SpaghettiVONGOLE",
    "name": "スープ入り塩味ボンゴレ",
    "price": 500,
    "calorie": 564,
    "salt": 3.0
}, {
    "order_code": "PA11",
    "name_en": "SpaghettiNERODISEPPIA",
    "name": "イカの墨入りスパゲッティ",
    "price": 500,
    "calorie": 578,
    "salt": 2.4
}, {
    "order_code": "PA12",
    "name_en": "SpaghettiwithMeatSauce",
    "name": "ミートソースボロニア風",
    "price": 400,
    "calorie": 571,
    "salt": 2.8
}, {
    "order_code": "PA13",
    "name_en": "SpaghettiPEPERONCINOwithCabbage&Bacon",
    "name": "キャベツのペペロンチーノ",
    "price": 400,
    "calorie": 663,
    "salt": 1.9
}, {
    "order_code": "PA51",
    "name_en": "SpaghettiTARAKOSauce",
    "name": "タラコソースシシリー風 Wサイズ",
    "price": 600,
    "calorie": 825,
    "salt": 3.0
}, {
    "order_code": "PA52",
    "name_en": "SpaghettiwithMeatSauce",
    "name": "ミートソースボロニア風 Wサイズ",
    "price": 600,
    "calorie": 856,
    "salt": 4.2
}, {
    "order_code": "PA53",
    "name_en": "SpaghettiPEPERONCINO",
    "name": "ペペロンチーノ Wサイズ",
    "price": 450,
    "calorie": 676,
    "salt": 2.8
}, {
    "order_code": "PA54",
    "name_en": "SpaghettiwithTomato&Bacon",
    "name": "パルマ風スパゲッティ Wサイズ",
    "price": 600,
    "calorie": 1074,
    "salt": 4.1
}, {
    "order_code": "PA55",
    "name_en": "SpaghettiCARBONARA",
    "name": "カルボナーラ Wサイズ",
    "price": 700,
    "calorie": 1033,
    "salt": 2.9
}, {
    "order_code": "PA56",
    "name_en": "SpaghettiwithShrimp&Broccoli,Tomato&Cream",
    "name": "エビとブロッコリーのオーロラソース Wサイズ",
    "price": 700,
    "calorie": 1160,
    "salt": 3.5
}, {
    "order_code": "PA58",
    "name_en": "SpaghettiAGLIOOLIO",
    "name": "アーリオ・オーリオ Wサイズ",
    "price": 450,
    "calorie": 745,
    "salt": 2.4
}, {
    "order_code": "PA59",
    "name_en": "ShortPastawithTomatoBacon&Chilli",
    "name": "アラビアータ Wサイズ",
    "price": 600,
    "calorie": 1008,
    "salt": 3.9
}, {
    "order_code": "PA61",
    "name_en": "SpaghettiNERODISEPPIA",
    "name": "イカの墨入りスパゲッティ Wサイズ",
    "price": 700,
    "calorie": 809,
    "salt": 3.4
}, {
    "order_code": "PA63",
    "name_en": "SpaghettiPEPERONCINOwithCabbage&Bacon",
    "name": "キャベツのペペロンチーノ Wサイズ",
    "price": 600,
    "calorie": 995,
    "salt": 2.9
}, {
    "order_code": "PZ01",
    "name_en": "PIZZAwithBuffaloMozzarellaCheese",
    "name": "マルゲリータピザ",
    "price": 400,
    "calorie": 568,
    "salt": 2.5
}, {
    "order_code": "PZ02",
    "name_en": "PIZZAwithTripleBuffaloMozzarellaCheese",
    "name": "バッファローモッツァレラのピザ",
    "price": 500,
    "calorie": 575,
    "salt": 2.3
}, {
    "order_code": "PZ03",
    "name_en": "PIZZAwithBacon",
    "name": "パンチェッタのピザ",
    "price": 400,
    "calorie": 646,
    "salt": 2.9
}, {
    "order_code": "PZ04",
    "name_en": "PIZZAwithMushroom&VegetableSalsa",
    "name": "野菜ときのこのピザ",
    "price": 400,
    "calorie": 593,
    "salt": 2.9
}, {
    "order_code": "PZ05",
    "name_en": "CornPIZZAwithWhiteSauce",
    "name": "たっぷりコーンのピザ",
    "price": 400,
    "calorie": 669,
    "salt": 2.8
}, {
    "order_code": "PZ06",
    "name_en": "PIZZAwithRocket&Anchovy",
    "name": "アンチョビとルーコラのピザ",
    "price": 400,
    "calorie": 543,
    "salt": 4.7
}, {
    "order_code": "PZ08",
    "name_en": "SausagePIZZAwithWhiteSauce",
    "name": "ソーセージピザ",
    "price": 400,
    "calorie": 759,
    "salt": 4.1
}, {
    "order_code": "PZ51",
    "name_en": "PIZZAwithBuffaloMozzarellaCheese",
    "name": "マルゲリータピザ Wチーズ",
    "price": 500,
    "calorie": 710,
    "salt": 3.1
}, {
    "order_code": "PZ52",
    "name_en": "PIZZAwithTripleBuffaloMozzarellaCheese",
    "name": "バッファローモッツァレラのピザ Wチーズ",
    "price": 600,
    "calorie": 690,
    "salt": 2.8
}, {
    "order_code": "PZ53",
    "name_en": "PIZZAwithBacon",
    "name": "パンチェッタのピザ Wチーズ",
    "price": 500,
    "calorie": 808,
    "salt": 3.6
}, {
    "order_code": "PZ54",
    "name_en": "PIZZAwithMushroom&VegetableSalsa",
    "name": "野菜ときのこのピザ Wチーズ",
    "price": 500,
    "calorie": 741,
    "salt": 3.6
}, {
    "order_code": "PZ55",
    "name_en": "CornPIZZAwithWhiteSauce",
    "name": "たっぷりコーンのピザ Wチーズ",
    "price": 500,
    "calorie": 836,
    "salt": 3.5
}, {
    "order_code": "PZ56",
    "name_en": "PIZZAwithRocket&Anchovy",
    "name": "アンチョビとルーコラのピザ Wチーズ",
    "price": 500,
    "calorie": 679,
    "salt": 5.9
}, {
    "order_code": "PZ58",
    "name_en": "SausagePIZZAwithWhiteSauce",
    "name": "ソーセージピザ Wチーズ",
    "price": 500,
    "calorie": 607,
    "salt": 5.1
}, {
    "order_code": "RP01",
    "name_en": "Rice",
    "name": "ライス",
    "price": 150,
    "calorie": 303,
    "salt": 0.0
}, {
    "order_code": "RP02",
    "name_en": "LargeRice",
    "name": "ラージライス",
    "price": 200,
    "calorie": 454,
    "salt": 0.0
}, {
    "order_code": "RP03",
    "name_en": "SmallRice",
    "name": "スモールライス",
    "price": 100,
    "calorie": 151,
    "salt": 0.0
}, {
    "order_code": "RP04",
    "name_en": "FocacciawithCinnamonSugar",
    "name": "シナモンプチフォッカ",
    "price": 200,
    "calorie": 246,
    "salt": 0.8
}, {
    "order_code": "RP05",
    "name_en": "SetPetitFocaccia",
    "name": "セットプチフォッカ",
    "price": 100,
    "calorie": 107,
    "salt": 0.4
}, {
    "order_code": "RP06",
    "name_en": "PetitFocaccia",
    "name": "プチフォッカ",
    "price": 150,
    "calorie": 214,
    "salt": 0.8
}, {
    "order_code": "RP08",
    "name_en": "MiniFicelle",
    "name": "ミニフィセル",
    "price": 150,
    "calorie": 188,
    "salt": 1.0
}, {
    "order_code": "RP09",
    "name_en": "GarlicToast",
    "name": "ガーリックトースト",
    "price": 200,
    "calorie": 252,
    "salt": 1.1
}, {
    "order_code": "SA01",
    "name_en": "ShrimpSalad",
    "name": "小エビのサラダ Lサイズ",
    "price": 500,
    "calorie": 189,
    "salt": 2.1
}, {
    "order_code": "SA02",
    "name_en": "ShrimpSalad",
    "name": "小エビのサラダ",
    "price": 350,
    "calorie": 126,
    "salt": 1.4
}, {
    "order_code": "SA03",
    "name_en": "RocketSaladwithPecorinoCheese&Olive",
    "name": "彩りイタリアンサラダ Lサイズ",
    "price": 500,
    "calorie": 321,
    "salt": 2.2
}, {
    "order_code": "SA04",
    "name_en": "RocketSaladwithPecorinoCheese&Olive",
    "name": "彩りイタリアンサラダ",
    "price": 350,
    "calorie": 214,
    "salt": 1.5
}, {
    "order_code": "SA05",
    "name_en": "SaladwithChicken&Broccoli",
    "name": "チキンとブロッコリーのサラダ Lサイズ",
    "price": 500,
    "calorie": 274,
    "salt": 2.5
}, {
    "order_code": "SA06",
    "name_en": "SaladwithChicken&Broccoli",
    "name": "チキンとブロッコリーのサラダ",
    "price": 350,
    "calorie": 182,
    "salt": 1.7
}, {
    "order_code": "SA07",
    "name_en": "SaladSeaweedwithOkra",
    "name": "わかめとオクラのサラダ Lサイズ",
    "price": 500,
    "calorie": 214,
    "salt": 4.4
}, {
    "order_code": "SA08",
    "name_en": "SaladSeaweedwithOkra",
    "name": "わかめとオクラのサラダ",
    "price": 350,
    "calorie": 143,
    "salt": 3.0
}, {
    "order_code": "SU01",
    "name_en": "CreamCornSoup",
    "name": "コーンクリームスープ",
    "price": 150,
    "calorie": 142,
    "salt": 1.1
}, {
    "order_code": "SU02",
    "name_en": "ClamChowderwithChineseCabbage",
    "name": "白菜のクラムチャウダー",
    "price": 300,
    "calorie": 281,
    "salt": 1.8
}, {
    "order_code": "SU03",
    "name_en": "MushroomSoup",
    "name": "マッシュルームスープ",
    "price": 150,
    "calorie": 130,
    "salt": 0.9
}, {
    "order_code": "SU04",
    "name_en": "OnionSoupwithBread&Cheese",
    "name": "たまねぎのズッパ",
    "price": 300,
    "calorie": 223,
    "salt": 1.8
}, {
    "order_code": "TP01",
    "name_en": "topping",
    "name": "トッピング半熟卵",
    "price": 50,
    "calorie": 90,
    "salt": 0.2
}, {
    "order_code": "TP02",
    "name_en": "topping",
    "name": "ペコリーノ・ロマーノ",
    "price": 100,
    "calorie": 78,
    "salt": 0.8
}, {
    "order_code": "TP03",
    "name_en": "topping",
    "name": "ガルムソース&野菜ペースト",
    "price": 150,
    "calorie": 99,
    "salt": 1.1
}, {
    "order_code": "TP04",
    "name_en": "topping",
    "name": "野菜ペースト",
    "price": 100,
    "calorie": 72,
    "salt": 0.3
}, {
    "order_code": "TP06",
    "name_en": "topping",
    "name": "やみつきスパイス",
    "price": 50,
    "calorie": 6,
    "salt": 1.4
}, {
    "order_code": "TP07",
    "name_en": "topping",
    "name": "フルーツソース(カシス&ブルーベリー)",
    "price": 100,
    "calorie": 40,
    "salt": 0.0
}, {
    "order_code": "WN01",
    "name_en": "Alcohol",
    "name": "グラスワイン 赤",
    "price": 100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN02",
    "name_en": "Alcohol",
    "name": "グラスワイン 白",
    "price": 100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN03",
    "name_en": "Alcohol",
    "name": "デカンタ 赤 250ml",
    "price": 200,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN04",
    "name_en": "Alcohol",
    "name": "デカンタ 白 250ml",
    "price": 200,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN05",
    "name_en": "Alcohol",
    "name": "デカンタ 赤 500ml",
    "price": 400,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN06",
    "name_en": "Alcohol",
    "name": "デカンタ 白 500ml",
    "price": 400,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN07",
    "name_en": "Alcohol",
    "name": "マグナム 赤 1500ml",
    "price": 1100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN08",
    "name_en": "Alcohol",
    "name": "マグナム 白 1500ml",
    "price": 1100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN12",
    "name_en": "Alcohol",
    "name": "ランブルスコ（ロゼ）",
    "price": 1100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN13",
    "name_en": "Alcohol",
    "name": "ドン ラファエロ",
    "price": 1100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN14",
    "name_en": "Alcohol",
    "name": "ランブルスコ セッコ",
    "price": 1100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN15",
    "name_en": "Alcohol",
    "name": "ベルデッキオ",
    "price": 1100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN16",
    "name_en": "Alcohol",
    "name": "キャンティ",
    "price": 1100,
    "calorie": 0,
    "salt": 0.0
}, {
    "order_code": "WN19",
    "name_en": "Alcohol",
    "name": "キャンティ ルフィナ リゼルバ",
    "price": 2200,
    "calorie": 0,
    "salt": 0.0
}]
