name: deploy to github pages
on:
  push:
    branches:
      - feature/refactor/v1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install
        working-directory: app
        run: yarn install
      - name: build
        working-directory: app
        run: |
          yarn run build
          touch out/.nojekyll
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/out
